INSERT INTO BAIRRO (id_bairro, nome, zona, fk_id_cidade) VALUES 
(1, 'Centro', 'Centro', 1),
(2, 'São Cristóvão', 'Norte', 1),
(3, 'Tamboril', 'Sul', 1),
(4, 'Boa Vista', 'Leste', 1),
(5, 'Centro', 'Centro', 2),
(6, 'Alto dos Santos', 'Norte', 2),
(7, 'Centro', 'Centro', 3),
(8, 'Santo Afonso', 'Oeste', 3),
(9, 'Iraque', 'Leste', 3),
(10, 'Centro', 'Centro', 4),
(11, 'Parmênates', 'Sul', 4),
(12, 'São Rafael', 'Norte', 4),
(13, 'Centro', 'Centro', 5),
(14, 'Bela Vista', 'Oeste', 5),
(15, 'Centro', 'Centro', 6),
(16, 'São Cristóvão', 'Leste', 6),
(17, 'Vila Maria', 'Sul', 6),
(18, 'Centro', 'Centro', 7),
(19, 'Cohab', 'Norte', 7),
(20, 'Centro', 'Centro', 8),
(21, 'Bairro do Matadouro', 'Sul', 8),
(22, 'Centro', 'Centro', 9),
(23, 'Socorro', 'Norte', 9),
(24, 'Planalto', 'Leste', 9),
(25, 'Bairro Novo', 'Oeste', 9),
(26, 'Centro', 'Centro', 10),
(27, 'Xucurus', 'Oeste', 10),
(28, 'Centenário', 'Norte', 10),
(29, 'Prado', 'Sul', 10),
(30, 'Vila Anápolis', 'Leste', 10);
